// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Error returned by the Valorant Tauri commands.
 *
 * Serializes to `{ "kind": "...", "message": "..." }` so the frontend can
 * branch on `kind` (e.g. show the demo/offline state on `notAvailable`,
 * prompt for a region on `needRegion`).
 */
export type AppError = { "kind": "notAvailable", message: string, } | { "kind": "needRegion", message: string, } | { "kind": "notInMatch", message: string, } | { "kind": "unauthorized", message: string, } | { "kind": "http", message: string, } | { "kind": "parse", message: string, };
