// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LobbyPlayer } from "./LobbyPlayer";
import type { RiotShard } from "./RiotShard";

/**
 * Result of `get_current_match` (mirrors `CurrentMatch` on TS side).
 */
export type CurrentMatch = { 
/**
 * "menus" | "pregame" | "coregame".
 */
phase: string, matchId?: string, players: Array<LobbyPlayer>, shard: RiotShard, };
