// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A friend currently playing, with what the client publishes about them.
 */
export type FriendPresence = { puuid: string, gameName?: string, tagLine?: string, 
/**
 * "MENUS", "PREGAME" or "INGAME".
 */
sessionLoopState?: string, partySize?: number, maxPartySize?: number, queueId?: string, competitiveTier?: number, };
