// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A player on the signed-in user's friend list.
 */
export type Friend = { puuid: string, gameName?: string, tagLine?: string, region?: string, note?: string, };
