// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A player discovered in the current lobby (mirrors `LobbyPlayer` on TS side).
 */
export type LobbyPlayer = { puuid: string, teamId: string, agentId?: string, isAlly: boolean, isSelf: boolean, };
