// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Auth context + identity returned by `get_local_tokens` and accepted back as
 * input by `get_current_match`. Mirrors `RiotAuth` + `RiotShard` on the TS side.
 *
 * Tokens live in frontend memory only and are never persisted.
 */
export type LocalTokens = { accessToken: string, entitlementToken: string, 
/**
 * Game client version, e.g. "release-09.00-shipping-...".
 */
clientVersion: string, puuid: string, region: string, shard: string, };
