// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lockfile metadata exposed to the frontend.
 *
 * The password is intentionally **not** part of this struct — it never leaves
 * the Rust side.
 */
export type LockfileInfo = { name: string, pid: number, port: number, protocol: string, };
