// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Region/shard pair (mirrors `RiotShard` on the TS side).
 */
export type RiotShard = { region: string, shard: string, };
